// Code generated by Slice Machine. DO NOT EDIT.

import EventCards from './EventCards';
import Hero from './Hero';
import TextWithImage from './TextWithImage';

export {
	EventCards,
	Hero,
	TextWithImage,
};

export const components = {
	event_cards: EventCards,
	hero: Hero,
	text_with_image: TextWithImage,
};
