import Head from "next/head";
import Image from "next/image";
import { createClient } from "../prismicio";
import type { InferGetStaticPropsType, GetStaticPropsContext } from "next";

type PageProps = InferGetStaticPropsType<typeof getStaticProps>;

export default function Home({ page }: PageProps) {
  console.log(page);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
    </div>
  );
}

export async function getStaticProps({
  locale,
  previewData,
}: GetStaticPropsContext) {
  const client = createClient({ previewData });

  const page = await client.getByUID("page", "home", { lang: locale });
  // const navigation = await client.getSingle("navigation", { lang: locale });
  // const settings = await client.getSingle("settings", { lang: locale });
  // const footer = await client.getSingle("footer", { lang: locale });

  return {
    props: {
      page,
      // navigation,
      // settings,
      // footer,
    },
  };
}
